version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.0
    working_directory: ~/app
    steps:
      - checkout
      - run: npm -v
      - run: node -v
      - run: npm install
      - run: npm run lint
      - run: npm audit
